/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package com.barassolutions;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int AT = 10;
  /** RegularExpression Id. */
  int ATTR = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int CASE = 13;
  /** RegularExpression Id. */
  int CATCH = 14;
  /** RegularExpression Id. */
  int CHOICE = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int COLLECT = 17;
  /** RegularExpression Id. */
  int COND = 18;
  /** RegularExpression Id. */
  int CONTINUE = 19;
  /** RegularExpression Id. */
  int DECLARE = 20;
  /** RegularExpression Id. */
  int DEFINE = 21;
  /** RegularExpression Id. */
  int DEF = 22;
  /** RegularExpression Id. */
  int DEFPROC = 23;
  /** RegularExpression Id. */
  int DEFLT = 24;
  /** RegularExpression Id. */
  int DIS = 25;
  /** RegularExpression Id. */
  int DO = 26;
  /** RegularExpression Id. */
  int ELSE = 27;
  /** RegularExpression Id. */
  int EXPORT = 28;
  /** RegularExpression Id. */
  int EXTENDS = 29;
  /** RegularExpression Id. */
  int FAIL = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int FEAT = 32;
  /** RegularExpression Id. */
  int FINALLY = 33;
  /** RegularExpression Id. */
  int FOR = 34;
  /** RegularExpression Id. */
  int FROM = 35;
  /** RegularExpression Id. */
  int FUNCTOR = 36;
  /** RegularExpression Id. */
  int IF = 37;
  /** RegularExpression Id. */
  int IMPORT = 38;
  /** RegularExpression Id. */
  int IN = 39;
  /** RegularExpression Id. */
  int LAZY = 40;
  /** RegularExpression Id. */
  int LOCK = 41;
  /** RegularExpression Id. */
  int MATCH = 42;
  /** RegularExpression Id. */
  int METH = 43;
  /** RegularExpression Id. */
  int NOT = 44;
  /** RegularExpression Id. */
  int OF = 45;
  /** RegularExpression Id. */
  int OR = 46;
  /** RegularExpression Id. */
  int PREPARE = 47;
  /** RegularExpression Id. */
  int PROP = 48;
  /** RegularExpression Id. */
  int RAISE = 49;
  /** RegularExpression Id. */
  int REQUIRE = 50;
  /** RegularExpression Id. */
  int RETURN = 51;
  /** RegularExpression Id. */
  int SKP = 52;
  /** RegularExpression Id. */
  int THIS = 53;
  /** RegularExpression Id. */
  int THREAD = 54;
  /** RegularExpression Id. */
  int TRUE = 55;
  /** RegularExpression Id. */
  int TRY = 56;
  /** RegularExpression Id. */
  int UNIT = 57;
  /** RegularExpression Id. */
  int VAL = 58;
  /** RegularExpression Id. */
  int VAR = 59;
  /** RegularExpression Id. */
  int ASSIGN = 60;
  /** RegularExpression Id. */
  int COLASSIGN = 61;
  /** RegularExpression Id. */
  int EQUAL = 62;
  /** RegularExpression Id. */
  int NE = 63;
  /** RegularExpression Id. */
  int LT = 64;
  /** RegularExpression Id. */
  int GT = 65;
  /** RegularExpression Id. */
  int LE = 66;
  /** RegularExpression Id. */
  int GE = 67;
  /** RegularExpression Id. */
  int LBARROW = 68;
  /** RegularExpression Id. */
  int IMPL = 69;
  /** RegularExpression Id. */
  int LAND = 70;
  /** RegularExpression Id. */
  int LOR = 71;
  /** RegularExpression Id. */
  int LNOT = 72;
  /** RegularExpression Id. */
  int LNOTNOT = 73;
  /** RegularExpression Id. */
  int MINUS = 74;
  /** RegularExpression Id. */
  int PLUS = 75;
  /** RegularExpression Id. */
  int STAR = 76;
  /** RegularExpression Id. */
  int SLASH = 77;
  /** RegularExpression Id. */
  int BACKSLASH = 78;
  /** RegularExpression Id. */
  int MODULO = 79;
  /** RegularExpression Id. */
  int HASHTAG = 80;
  /** RegularExpression Id. */
  int UNDERSCORE = 81;
  /** RegularExpression Id. */
  int DOLLAR = 82;
  /** RegularExpression Id. */
  int APOSTROPHE = 83;
  /** RegularExpression Id. */
  int QUOTE = 84;
  /** RegularExpression Id. */
  int LACCENT = 85;
  /** RegularExpression Id. */
  int RACCENT = 86;
  /** RegularExpression Id. */
  int HAT = 87;
  /** RegularExpression Id. */
  int BOX = 88;
  /** RegularExpression Id. */
  int TILDE = 89;
  /** RegularExpression Id. */
  int DEGREE = 90;
  /** RegularExpression Id. */
  int COMMERCAT = 91;
  /** RegularExpression Id. */
  int LARROW = 92;
  /** RegularExpression Id. */
  int RARROW = 93;
  /** RegularExpression Id. */
  int FDASSIGN = 94;
  /** RegularExpression Id. */
  int FDNE = 95;
  /** RegularExpression Id. */
  int FDLT = 96;
  /** RegularExpression Id. */
  int FDLE = 97;
  /** RegularExpression Id. */
  int FDGT = 98;
  /** RegularExpression Id. */
  int FDGE = 99;
  /** RegularExpression Id. */
  int COLCOL = 100;
  /** RegularExpression Id. */
  int COLCOLCOL = 101;
  /** RegularExpression Id. */
  int COMMA = 102;
  /** RegularExpression Id. */
  int LBRACK = 103;
  /** RegularExpression Id. */
  int LCURLY = 104;
  /** RegularExpression Id. */
  int LPAREN = 105;
  /** RegularExpression Id. */
  int RBRACK = 106;
  /** RegularExpression Id. */
  int RCURLY = 107;
  /** RegularExpression Id. */
  int RPAREN = 108;
  /** RegularExpression Id. */
  int SEMI = 109;
  /** RegularExpression Id. */
  int COLON = 110;
  /** RegularExpression Id. */
  int DOT = 111;
  /** RegularExpression Id. */
  int DOTDOT = 112;
  /** RegularExpression Id. */
  int ELLIPSIS = 113;
  /** RegularExpression Id. */
  int VARIABLE = 114;
  /** RegularExpression Id. */
  int ATOM = 115;
  /** RegularExpression Id. */
  int LABEL = 116;
  /** RegularExpression Id. */
  int IDENTIFIER = 117;
  /** RegularExpression Id. */
  int INT_LITERAL = 118;
  /** RegularExpression Id. */
  int FLOAT = 119;
  /** RegularExpression Id. */
  int STRING = 120;
  /** RegularExpression Id. */
  int CHAR = 121;
  /** RegularExpression Id. */
  int BOOLEAN = 122;
  /** RegularExpression Id. */
  int DECINT = 123;
  /** RegularExpression Id. */
  int HEXINT = 124;
  /** RegularExpression Id. */
  int OCTINT = 125;
  /** RegularExpression Id. */
  int BININT = 126;
  /** RegularExpression Id. */
  int LETTER = 127;
  /** RegularExpression Id. */
  int DIGIT = 128;
  /** RegularExpression Id. */
  int OCTDIGIT = 129;
  /** RegularExpression Id. */
  int HEXDIGIT = 130;
  /** RegularExpression Id. */
  int BINDIGIT = 131;
  /** RegularExpression Id. */
  int NON_ZERO_DIGIT = 132;
  /** RegularExpression Id. */
  int UPPERCASE = 133;
  /** RegularExpression Id. */
  int LOWERCASE = 134;
  /** RegularExpression Id. */
  int CHARINT = 135;
  /** RegularExpression Id. */
  int ALPHANUM = 136;
  /** RegularExpression Id. */
  int ATOM_CHAR = 137;
  /** RegularExpression Id. */
  int STRING_CHAR = 138;
  /** RegularExpression Id. */
  int VARIABLE_CHAR = 139;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 140;
  /** RegularExpression Id. */
  int PSEUDO_CHAR = 141;
  /** RegularExpression Id. */
  int ERROR = 142;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTI_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 9>",
    "\"at\"",
    "\"attr\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"choice\"",
    "\"class\"",
    "\"collect\"",
    "\"cond\"",
    "\"continue\"",
    "\"declare\"",
    "\"define\"",
    "\"def\"",
    "\"defproc\"",
    "\"default\"",
    "\"dis\"",
    "\"do\"",
    "\"else\"",
    "\"export\"",
    "\"extends\"",
    "\"fail\"",
    "\"false\"",
    "\"feat\"",
    "\"finally\"",
    "\"for\"",
    "\"from\"",
    "\"functor\"",
    "\"if\"",
    "\"import\"",
    "\"in\"",
    "\"lazy\"",
    "\"lock\"",
    "\"match\"",
    "\"meth\"",
    "\"not\"",
    "\"of\"",
    "\"or\"",
    "\"prepare\"",
    "\"prop\"",
    "\"raise\"",
    "\"require\"",
    "\"return\"",
    "\"skip\"",
    "\"this\"",
    "\"thread\"",
    "\"true\"",
    "\"try\"",
    "\"unit\"",
    "\"val\"",
    "\"var\"",
    "\"=\"",
    "\":=\"",
    "\"==\"",
    "\"\\\\=\"",
    "\"<\"",
    "\">\"",
    "\"=<\"",
    "\">=\"",
    "\"<=\"",
    "\"=>\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"!!\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"\\\\\"",
    "\"%\"",
    "\"#\"",
    "\"_\"",
    "\"$\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"`\"",
    "\"\\u00b4\"",
    "\"^\"",
    "\"[]\"",
    "\"~\"",
    "\"\\u00b0\"",
    "\"@\"",
    "\"<-\"",
    "\"->\"",
    "\"=:\"",
    "\"\\\\=:\"",
    "\"<:\"",
    "\"=<:\"",
    "\">:\"",
    "\">=:\"",
    "\"::\"",
    "\":::\"",
    "\",\"",
    "\"[\"",
    "\"{\"",
    "\"(\"",
    "\"]\"",
    "\"}\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"..\"",
    "\"...\"",
    "<VARIABLE>",
    "<ATOM>",
    "<LABEL>",
    "<IDENTIFIER>",
    "<INT_LITERAL>",
    "<FLOAT>",
    "<STRING>",
    "<CHAR>",
    "<BOOLEAN>",
    "<DECINT>",
    "<HEXINT>",
    "<OCTINT>",
    "<BININT>",
    "<LETTER>",
    "<DIGIT>",
    "<OCTDIGIT>",
    "<HEXDIGIT>",
    "<BINDIGIT>",
    "<NON_ZERO_DIGIT>",
    "<UPPERCASE>",
    "<LOWERCASE>",
    "<CHARINT>",
    "<ALPHANUM>",
    "<ATOM_CHAR>",
    "<STRING_CHAR>",
    "<VARIABLE_CHAR>",
    "<ESCAPE_CHAR>",
    "<PSEUDO_CHAR>",
    "<ERROR>",
  };

}
