/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package com.barassolutions;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int AT = 11;
  /** RegularExpression Id. */
  int ATTR = 12;
  /** RegularExpression Id. */
  int BREAK = 13;
  /** RegularExpression Id. */
  int CASE = 14;
  /** RegularExpression Id. */
  int CATCH = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int CONTINUE = 17;
  /** RegularExpression Id. */
  int DECLARE = 18;
  /** RegularExpression Id. */
  int DEF = 19;
  /** RegularExpression Id. */
  int DEFPROC = 20;
  /** RegularExpression Id. */
  int DO = 21;
  /** RegularExpression Id. */
  int ELSE = 22;
  /** RegularExpression Id. */
  int EXPORT = 23;
  /** RegularExpression Id. */
  int EXTENDS = 24;
  /** RegularExpression Id. */
  int FALSE = 25;
  /** RegularExpression Id. */
  int FINALLY = 26;
  /** RegularExpression Id. */
  int FOR = 27;
  /** RegularExpression Id. */
  int FROM = 28;
  /** RegularExpression Id. */
  int FUNCTOR = 29;
  /** RegularExpression Id. */
  int IF = 30;
  /** RegularExpression Id. */
  int IMPORT = 31;
  /** RegularExpression Id. */
  int IN = 32;
  /** RegularExpression Id. */
  int LAZY = 33;
  /** RegularExpression Id. */
  int LOCK = 34;
  /** RegularExpression Id. */
  int MATCH = 35;
  /** RegularExpression Id. */
  int NIL = 36;
  /** RegularExpression Id. */
  int OR = 37;
  /** RegularExpression Id. */
  int PROP = 38;
  /** RegularExpression Id. */
  int RAISE = 39;
  /** RegularExpression Id. */
  int RETURN = 40;
  /** RegularExpression Id. */
  int SKP = 41;
  /** RegularExpression Id. */
  int SUPER = 42;
  /** RegularExpression Id. */
  int THIS = 43;
  /** RegularExpression Id. */
  int THREAD = 44;
  /** RegularExpression Id. */
  int TRUE = 45;
  /** RegularExpression Id. */
  int TRY = 46;
  /** RegularExpression Id. */
  int UNIT = 47;
  /** RegularExpression Id. */
  int VAL = 48;
  /** RegularExpression Id. */
  int VAR = 49;
  /** RegularExpression Id. */
  int ASSIGN = 50;
  /** RegularExpression Id. */
  int PLUSASS = 51;
  /** RegularExpression Id. */
  int MINUSASS = 52;
  /** RegularExpression Id. */
  int DEFINE = 53;
  /** RegularExpression Id. */
  int EQUAL = 54;
  /** RegularExpression Id. */
  int NE = 55;
  /** RegularExpression Id. */
  int LT = 56;
  /** RegularExpression Id. */
  int GT = 57;
  /** RegularExpression Id. */
  int LE = 58;
  /** RegularExpression Id. */
  int GE = 59;
  /** RegularExpression Id. */
  int IMPL = 60;
  /** RegularExpression Id. */
  int LAND = 61;
  /** RegularExpression Id. */
  int LOR = 62;
  /** RegularExpression Id. */
  int LNOT = 63;
  /** RegularExpression Id. */
  int MINUS = 64;
  /** RegularExpression Id. */
  int PLUS = 65;
  /** RegularExpression Id. */
  int STAR = 66;
  /** RegularExpression Id. */
  int SLASH = 67;
  /** RegularExpression Id. */
  int MODULO = 68;
  /** RegularExpression Id. */
  int HASHTAG = 69;
  /** RegularExpression Id. */
  int UNDERSCORE = 70;
  /** RegularExpression Id. */
  int DOLLAR = 71;
  /** RegularExpression Id. */
  int APOSTROPHE = 72;
  /** RegularExpression Id. */
  int QUOTE = 73;
  /** RegularExpression Id. */
  int DEGREE = 74;
  /** RegularExpression Id. */
  int COLCOL = 75;
  /** RegularExpression Id. */
  int COMMA = 76;
  /** RegularExpression Id. */
  int LBRACK = 77;
  /** RegularExpression Id. */
  int LCURLY = 78;
  /** RegularExpression Id. */
  int LPAREN = 79;
  /** RegularExpression Id. */
  int RBRACK = 80;
  /** RegularExpression Id. */
  int RCURLY = 81;
  /** RegularExpression Id. */
  int RPAREN = 82;
  /** RegularExpression Id. */
  int SEMI = 83;
  /** RegularExpression Id. */
  int COLON = 84;
  /** RegularExpression Id. */
  int DOT = 85;
  /** RegularExpression Id. */
  int DOTDOT = 86;
  /** RegularExpression Id. */
  int ELLIPSIS = 87;
  /** RegularExpression Id. */
  int VARIABLESTRICT = 88;
  /** RegularExpression Id. */
  int VARIABLE = 89;
  /** RegularExpression Id. */
  int ATOM = 90;
  /** RegularExpression Id. */
  int ATOMLISP = 91;
  /** RegularExpression Id. */
  int STRING = 92;
  /** RegularExpression Id. */
  int CHARACTER = 93;
  /** RegularExpression Id. */
  int INT = 94;
  /** RegularExpression Id. */
  int FLOAT = 95;
  /** RegularExpression Id. */
  int UPPERCASE = 96;
  /** RegularExpression Id. */
  int LOWERCASE = 97;
  /** RegularExpression Id. */
  int LETTER = 98;
  /** RegularExpression Id. */
  int DIGIT = 99;
  /** RegularExpression Id. */
  int NON_ZERO_DIGIT = 100;
  /** RegularExpression Id. */
  int CHARINT = 101;
  /** RegularExpression Id. */
  int ALPHANUM = 102;
  /** RegularExpression Id. */
  int DECINT = 103;
  /** RegularExpression Id. */
  int HEXINT = 104;
  /** RegularExpression Id. */
  int OCTINT = 105;
  /** RegularExpression Id. */
  int BININT = 106;
  /** RegularExpression Id. */
  int OCTDIGIT = 107;
  /** RegularExpression Id. */
  int HEXDIGIT = 108;
  /** RegularExpression Id. */
  int BINDIGIT = 109;
  /** RegularExpression Id. */
  int ESCAPE_CHAR = 110;
  /** RegularExpression Id. */
  int ESC = 111;
  /** RegularExpression Id. */
  int CHARCHAR = 112;
  /** RegularExpression Id. */
  int PSEUDO_CHAR = 113;
  /** RegularExpression Id. */
  int ERROR = 114;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MULTI_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\b\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"at\"",
    "\"attr\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"continue\"",
    "\"declare\"",
    "\"def\"",
    "\"defproc\"",
    "\"do\"",
    "\"else\"",
    "\"export\"",
    "\"extends\"",
    "\"false\"",
    "\"finally\"",
    "\"for\"",
    "\"from\"",
    "\"functor\"",
    "\"if\"",
    "\"import\"",
    "\"in\"",
    "\"lazy\"",
    "\"lock\"",
    "\"match\"",
    "\"nil\"",
    "\"or\"",
    "\"prop\"",
    "\"raise\"",
    "\"return\"",
    "\"skip\"",
    "\"super\"",
    "\"this\"",
    "\"thread\"",
    "\"true\"",
    "\"try\"",
    "\"unit\"",
    "\"val\"",
    "\"var\"",
    "\"=\"",
    "\"+=\"",
    "\"-=\"",
    "\":=\"",
    "\"==\"",
    "\"\\\\=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"=>\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"-\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"#\"",
    "\"_\"",
    "\"$\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\"\\u00b0\"",
    "\"::\"",
    "\",\"",
    "\"[\"",
    "\"{\"",
    "\"(\"",
    "\"]\"",
    "\"}\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"..\"",
    "\"...\"",
    "<VARIABLESTRICT>",
    "<VARIABLE>",
    "<ATOM>",
    "<ATOMLISP>",
    "<STRING>",
    "<CHARACTER>",
    "<INT>",
    "<FLOAT>",
    "<UPPERCASE>",
    "<LOWERCASE>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<CHARINT>",
    "<ALPHANUM>",
    "<DECINT>",
    "<HEXINT>",
    "<OCTINT>",
    "<BININT>",
    "<OCTDIGIT>",
    "<HEXDIGIT>",
    "<BINDIGIT>",
    "<ESCAPE_CHAR>",
    "<ESC>",
    "<CHARCHAR>",
    "<PSEUDO_CHAR>",
    "<ERROR>",
  };

}
