package com.barassolutions.core;

//TODO the exact equivalent of this in j-- is JVariableDeclaration
// JVariableDeclarator has no equivalent in nozc. However it might be a good idea (or even necessary ?) to split assignments anyway

import com.barassolutions.BuiltIns;
import com.barassolutions.TokenOz;
import java.util.Map;

import com.barassolutions.Emitter;
import com.barassolutions.PrettyPrinter;

/**
 * The AST node for a local variable/method/etc. declaration. Local names are declared by analyze(),
 * which also re-writes any initializations as assignment statements, in turn generated by
 * codegen().
 */
public class DeclarationPart extends Statement {

  /**
   * Map holding declared variables and their optional assigned value.
   */
  private final Map<Variable, Expression> map;

  /**
   * Whether these variables are constants. Note that this concept is totally new to NewOz, since Oz
   * only supports constant values. In NewOz, one can declare variables, which are a wrapper for
   * Cells.
   */
  private boolean constant;

  public DeclarationPart(int line, Map<Variable, Expression> map, boolean constant) {
    super(line);
    this.map = map;
    this.constant = constant;
  }

  protected DeclarationPart(int line) {
    super(line);
  }

  @Override
  public AST analyze(Context context) {
    map.forEach((v, e) -> {
      //TODO declare v.name in context
      map.put(v, (Expression) e.analyze(context));
    });

    return this;
  }

  @Override
  public void codegen(Emitter output) {
    if (constant) {
      map.forEach((k, v) -> {
        output.literal(k.name());
        if (v != null) {
          output.token(TokenOz.ASSIGN);
          v.codegen(output);
        }
        output.newLine();
      });
    } else {
      map.forEach((k, v) -> {
        output.literal(k.name());
        output.token(TokenOz.ASSIGN);
        output.token(TokenOz.LCURLY);
        output.literal(BuiltIns.newCell(true));
        output.space();
        if (v == null) {
          output.token(TokenOz.UNDERSCORE);
        } else {
          v.codegen(output);
        }
        output.token(TokenOz.RCURLY);
        output.newLine();
      });
    }
  }

  @Override
  public void writeToStdOut(PrettyPrinter p) {
    if (constant) {
      map.forEach((k, v) -> {
        p.printf("<ConstantDeclaration line=\"%d\" name=\"%s\">\n", line(), k.name());
        p.indentRight();
        if (v == null) {
          p.printf("<Value : none>\n");
        } else {
          p.printf("<Value :>\n");
          v.writeToStdOut(p);
        }
        p.indentLeft();
        p.printf("</ConstantDeclaration>\n");
      });
    } else {
      map.forEach((k, v) -> {
        p.printf("<VariableDeclaration line=\"%d\" name=\"%s\">\n", line(), k.name());
        p.indentRight();
        if (v == null) {
          p.printf("<Initial value : none>\n");
        } else {
          p.printf("<Initial value :>\n");
          v.writeToStdOut(p);
        }
        p.indentLeft();
        p.printf("</VariableDeclaration>\n");
      });
    }
  }
}
