package com.barassolutions;

//TODO the exact equivalent of this in j-- is JVariableDeclaration
// JVariableDeclarator has no equivalent in nozc. However it might be a good idea (or even necessary ?) to split assignments anyway

/**
 * This class mirrors <code>Declaration</code>. However it is empty, as it doesn't make sense to
 * declare variables/values anonymously. Inheriting classes declare things like functors,
 * procedures, etc. Local names are declared by analyze(), which also re-writes any initializations
 * as assignment statements, in turn generated by codegen().
 */
public abstract class DeclarationAnonym extends Expression {

  /**
   * Construct an AST node for an expression given its line number.
   *
   * @param line line in which the expression occurs in the source file.
   */
  protected DeclarationAnonym(int line) {
    super(line);
  }
}
