package com.barassolutions;

/**
 * Token literal values and constants for Oz. Manually maintained.
 */
public enum TokenOz {

  EOF("<EOF>"),
  ANDTHEN("andthen"),
  AT("at"),
  ATTR("attr"),
  BREAK("break"),
  CASE("case"),
  CATCH("catch"),
  CHOICE("choice"),
  CLASS("class"),
  COLLECT("collect"),
  COND("cond"),
  CONTINUE("continue"),
  DECLARE("declare"),
  DEFAULT("default"),
  DEF("define"),
  DIS("dis"),
  DIV("div"),
  DO("do"),
  ELSE("else"),
  ELSECASE("elsecase"),
  ELSEIF("elseif"),
  ELSEOF("elseof"),
  END("end"),
  EXPORT("export"),
  FAIL("fail"),
  FALSE("false"),
  FEAT("feat"),
  FINALLY("finally"),
  FOR("for"),
  FROM("from"),
  FUN("fun"),
  FUNCTOR("functor"),
  IF("if"),
  IMPORT("import"),
  IN("in"),
  LAZY("lazy"),
  LOCAL("local"),
  LOCK("lock"),
  METH("meth"),
  MOD("mod"),
  NIL("nil"),
  NOT("not"),
  OF("of"),
  OR("or"),
  ORELSE("orelse"),
  PREPARE("prepare"),
  PROC("proc"),
  PROP("prop"),
  RAISE("raise"),
  REQUIRE("require"),
  RETURN("return"),
  SELF("self"),
  SKIP("skip"),
  THEN("then"),
  THREAD("thread"),
  TRUE("true"),
  TRY("try"),
  UNIT("unit"),

  ASSIGN("="),
  DEFINE(":="),
  EQUAL("=="),
  NE("\\="),
  LT("<"),
  GT(">"),
  LE("=<"),
  GE(">="),
  LBARROW("<="),
  AND("&"),
  PIPE("|"),
  LNOT("!"),
  LNOTNOT("!!"),
  MINUS("-"),
  PLUS("+"),
  STAR("*"),
  STARSTAR("**"),
  SLASH("/"),
  BACKSLASH("\\"),
  HASHTAG("#"),
  UNDERSCORE("_"),
  DOLLAR("$"),
  APOSTROPHE("'"),
  QUOTE("\""),
  LACCENT("`"),
  HAT("^"),
  BOX("[]"),
  WAVE("~"),
  COMMERCAT("@"),
  LARROW("<-"),
  FDASSIGN("=:"),
  FDNE("\\=:"),
  FDLT("<:"),
  FDLE("=<:"),
  FDGT(">:"),
  FDGE(">=:"),
  COLCOL("::"),
  COLCOLCOL(":::"),

  COMMA(","),
  DOT("."),
  LBRACK("["),
  LCURLY("{"),
  LPAREN("("),
  RBRACK("]"),
  RCURLY("}"),
  RPAREN(")"),
  COLON(":"),
  DOTDOT(".."),
  ELLIPSIS("...");


  private final String image;

  TokenOz(String image) {
    this.image = image;
  }

  public String image() {
    return this.image;
  }
}
